# Site settings
title: Conor Murphy - Product Design and Development Contractor
email: conormurphy@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A CV, portfolio and blog for Conor Murphy. A Product Design Contractor in Dublin, Ireland.
baseurl: ""
url: "http://itsconor.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
